- Quick setup:
    - Run command "npx playwright install" to install browser engines on local machine.
    - Ensure that solution has access to "C:\Users\{username}\AppData\Local\ms-playwright" and is able to run chromium engine.